---
title: "Publications"
---

En construction -- voir [CV](page_cv.qmd#Articles-and-working-manuscripts)

# Articles and working manuscripts

Mattavelli, S., <b>Béna, J.</b>, Unkelbach, C., & Corneille, O. (preprint). Repetition increases perceived truth of interpersonal statements from both politically congruent and incongruent sources. Preprint available at: [PsyArXiv version](https://osf.io/preprints/psyarxiv/4pwq2) 

<b>Béna, J.</b>, Lacassagne, D., & Corneille, O. (2024). Do Uncontrolled Processes Contribute to Evaluative Learning? Insights From a New Two-US Process Dissociation Procedure and Ambivalence Measures. _Quarterly Journal of Experimental Psychology_, [https://doi.org/10.1177/17470218241248138](https://doi.org/10.1177/17470218241248138). Preprint available at: [PsyArXiv version](https://osf.io/preprints/psyarxiv/g274k).

Mattavelli, S., <b>Béna, J.</b>, Unkelbach, C., & Corneille, O. (2024). People underestimate the influence of repetition on truth judgments (and more so for themselves than for others). _Cognition_, 105651. [https://doi.org/10.1016/j.cognition.2023.105651](https://doi.org/10.1016/j.cognition.2023.105651) \ Preprint available at: [PsyArXiv version](https://doi.org/10.31234/osf.io/5mwpz) 

<b>Béna, J.</b>, Rouard, M., & Corneille, O. (2023). You won't believe it! Truth judgments for clickbait headlines benefit (but less so) from prior exposure. _Applied Cognitive Psychology._ [https://doi.org/10.1002/acp.4134](https://doi.org/10.1002/acp.4134)

Corneille, O., & <b>Béna, J.</b> (2023). Instruction-based replication studies raise challenging questions for psychological science. _Collabra: Psychology, 9_(1), 82234. [https://doi.org/10.1525/collabra.82234](https://doi.org/10.1525/collabra.82234)

Stahl, C., <b>Béna, J.</b>, Aust, F., Mierop, A., & Corneille, O. (2023). A conditional judgment procedure for probing evaluative conditioning effects in the absence of feelings of remembering. _Behavior Research Methods._ [https://doi.org/10.3758/s13428-023-02081-w](https://doi.org/10.3758/s13428-023-02081-w) \ Preprint available at: [PsyArXiv version](https://psyarxiv.com/rtqnx/)

<b>Béna, J.</b>, Rihet, M., Carreras, O., & Terrier, P. (2023). Repetition could increase the perceived truth of conspiracy theories. _Psychonomic Bulletin & Review, 30_, 2397--2406. [https://doi.org/10.3758/s13423-023-02276-4](https://doi.org/10.3758/s13423-023-02276-4) \ Preprint available at: [PsyArXiv version](https://psyarxiv.com/3gc6k/)

<b>Béna, J.</b>, Mierop, A., Bancu, D., Unkelbach, C., & Corneille, O. (2023). The role of valence matching in the truth-by-repetition effect. _Social Cognition, 41_(2), 91--105. [https://doi.org/10.1521/soco.2023.41.2.193](https://doi.org/10.1521/soco.2023.41.2.193) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/369741504_The_Role_of_Valence_Matching_in_the_Truth-by-Repetition_Effect)

<b>Béna, J.</b>, Mauclet, A., & Corneille, O. (2023) Does mere co-occurrence influence evaluations independently of relational meaning? An investigation using subjective and objective ambivalence measures. _Journal of Experimental Psychology: General. 152_(4), 968–-992. [https://doi.org/10.1037/xge0001308](https://doi.org/10.1037/xge0001308) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/363660570_Does_Co-Occurrence_Information_Influence_Evaluations_Beyond_Relational_Meaning_An_Investigation_Using_Self-Reported_and_Mouse-Tracking_Measures_of_Attitudinal_Ambivalence)

<b>Béna, J.</b>, Corneille, O., Mierop, A., & Unkelbach, C. (2022). Robustness tests provide further support for an ecological account of the truth and fake news by repetition effects. Accepted at _International Review of Social Psychology, 35_(1), 19, 1--11. [https://doi.org/10.5334/irsp.683](https://doi.org/10.5334/irsp.683)

<b>Béna, J.</b>, Melnikoff, D., Mierop, A., & Corneille, O. (2022). Revisiting dissociation hypotheses with a structural fit approach: The case of the prepared reflex framework. _Journal of Experimental Social Psychology, 100_, 104297. [https://doi.org/10.1016/j.jesp.2022.104297](https://doi.org/10.1016/j.jesp.2022.104297) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/358142779_Revisiting_Dissociation_Hypotheses_with_a_Structural_fit_Approach_The_Case_of_the_Prepared_Reflex_Framework)

Corneille, O., & <b>Béna, J.</b> (2022). The “implicit bias” wording is a relic. Let's move on and study unconscious social categorization effects. Commentary on the target article "Implicit bias ≠ Bias on Implicit Measures" from Gawronski, B, Ledgerwood, A., & Eastwick, P. W.. _Psychological Inquiry, 33_(3), 167--172. [https://doi.org/10.1080/1047840X.2022.2106754](https://doi.org/10.1080/1047840X.2022.2106754) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/361511604_The_implicit_bias_wording_is_a_relic_Let's_move_on_and_study_unconscious_social_categorization_effects)

Lacassagne, D., <b>Béna, J.</b>, & Corneille, O. (2022). Is Earth a Perfect Square? Repetition Increases the Perceived Truth of Highly Implausible Statements. _Cognition, 223_, 105052. [https://doi.org/10.1016/j.cognition.2022.105052](https://doi.org/10.1016/j.cognition.2022.105052) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/358280796_Is_Earth_a_Perfect_Square_Repetition_Increases_the_Perceived_Truth_of_Highly_Implausible_Statements)

Mierop, A., Mikolajczak, M., Stahl, C., <b>Béna, J.</b>, Luminet, O., Lane, A., & Corneille, O. (2020). How Can Intranasal Oxytocin Research Be Trusted? A Systematic Review of the Interactive Effects of Intranasal Oxytocin on Psychosocial Outcomes. _Perspectives on Psychological Science, 15(5)_, 1228–1242. [https://doi.org/10.1177/1745691620921525](https://doi.org/10.1177/1745691620921525) \ Available at: [ResearchGate version](https://www.researchgate.net/publication/339566469_How_Can_Intranasal_Oxytocin_Research_Be_Trusted_A_Systematic_Review_of_the_Interactive_Effects_of_Intranasal_Oxytocin_on_Psychosocial_Outcomes)

<b>Béna, J.</b>, Carreras, O., & Terrier, P. (2019). L’effet de vérité induit par la répétition: Revue critique de l’hypothèse de familiarité [The repetition-induced truth effect: A critical note on the familiarity hypothesis]. _L'Année Psychologique, 119(3)_, 397–424. [https://doi.org/10.3917/anpsy1.193.0397](https://doi.org/10.3917/anpsy1.193.0397)

<b>Béna, J.</b>, Carreras, O., & Terrier, P. (preprint). On Believing Conspiracy Theories We Remember: Analyses of Two Large-Scale Surveys of Conspiracism in the French General Public. In revision. [Link to the preprint](https://doi.org/10.31234/osf.io/tf76n). 