---
title: "Thématiques TER (Master)"
---

<br>
<center>
<h3>Expression de la mémoire dans les croyances et les attitudes</h3>
</center>
<br>

<div style="text-align: justify"> 
La mémoire ne s’exprime pas seulement quand nous avons pour tâche de rappeler ou reconnaître des items : elle s’exprime également quand l’objet n’est pas, en apparence, la mémoire. Le TER pourra aborder diverses questions sur les phénomènes présentés ci-dessous ou apparentés. Certaines questions à préciser sont suggérées ci-dessous. 
</div>

<div style="text-align: justify"> 
_- Mémoire et croyances._ L’exposition répétée à des informations, vraies comme fausses, augmente leur vérité perçue. Cet "effet de vérité" est un phénomène de mémoire au sens où il représente un avantage de vérité perçue pour des affirmations étudiées (anciennes) vs. non-étudiées (nouvelles). 
</div>

<div style="text-align: justify"> 
Quels sont les processus (e.g., familiarité ; récollection) et représentations (e.g., gist ; verbatim) impliqués dans l'effet de vérité ? Sous quelles conditions est-il possible de réduire voire de renverser l'effet de vérité ? Des réplications (directes ou directes+) sont possibles<b>*</b>.
</div>

<b>*</b> Voici une thématique pour une réplication sur l'effet de vérité :

<h5>Croire des fake news parce qu'elles sont répétées ? Réplication de [Pennycook et al. (2018)](https://doi.org/10.1037/xge0000465)</h5><br>

<div style="text-align: justify"> 
L'effet de vérité est souvent mis en évidence avec des informations considérées comme peu importantes (Henderson et al., 2021). Cependant, des travaux récents suggèrent que l'exposition répétée pourrait également augmenter la vérité perçue d'informations problématiques. Par exemple, l'effet de vérité a été mis en évidence avec des 'fake news,' c'est-à-dire des informations entièrement fabriquées et souvent partisanes qui imitent le contenu des médias d'information dans leur présentation (Pennycoook et al., 2018).
</div>

<div style="text-align: justify"> 
La réplication de résultats est centrale dans l'accumulation de connaissances (e.g., [Nosek & Errington, 2020](https://doi.org/10.1371/journal.pbio.3000691)), mais a fait et fait encore l'objet de problèmes et préoccupations en psychologie (e.g., [Open Science Collaboration, 2015](https://doi.org/10.1126/science.aac4716)). L'effet de vérité avec des fake news est un phénomène avec des implications théoriques (conditions limites de l'effet de vérité) et appliquées (e.g., fonctionnement démocratique) importantes, justifiant de chercher à le répliquer. Le mémoire réalisé pourra viser à répliquer les résultats de [Pennycook et al. (2018, étude 2)](https://doi.org/10.1037/xge0000465) en suivant la procédure proposée par le Collaborative Replication & Education Project (CREP, voir [https://www.crep-psych.org/](https://www.crep-psych.org/)). Un TER/mémoire sur cette thématique implique de participer à la rédaction de documents en anglais et de travailler dans un environnement collaboratif impliquant des enseignant.e.s-chercheur.e.s de différentes universités.
</div><br><br>

<div style="text-align: justify"> 
_- Mémoire et attitudes._ Présenter de façon répétée des stimuli initialement neutres avec des stimuli valencés positivement ou négativement modifie l’évaluation des stimuli initialement neutres dans la direction des stimuli valencés avec lesquels ils apparaissent. Cet "effet de conditionnement évaluatif" est un phénomène de mémoire (associative) au sens où il représente un avantage d’évaluations positives pour les stimuli initialement neutres qui ont été présentés avec des stimuli positifs plutôt que négatifs. 
</div>

<div style="text-align: justify"> 
L’effet de conditionnement évaluatif est-il pour partie automatique (non-conscient ; incontrôlé) ? La simple co-occurrence entre les stimuli influence-t-elle les évaluations au-delà de la relation qu’ils entretiennent ? Des réplications (directes ou directes+) sont envisageables.
</div><br>

<div style="text-align: justify"> 
*Mots clés :* _conditionnement évaluatif ; croyances ; effet de vérité ; évaluations ; mémoire_
</div>